config/routes.rb
Rails.application.routes.draw do
  root 'snippets#index'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :snippets do
    member do 
      get :share, to: :share_form
      post :share
    end

    collection do 
      get :search
      get :my_gists
    end
  end

  devise_for :users, skip: [:sessions], controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  as :user do
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth['uid'], provider: auth['provider'])
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  include RailsAdmin::Snippet
  attr_accessor :email

  belongs_to :user

  has_many :tagables, dependent: :destroy
  has_many :tags, through: :tagables, :source => :tag

  validates :title,   presence: true

  enum status: ['Personal', 'Share']

  scope :recent, -> { order(created_at: :desc) }

  delegate :username, to: :user, allow_nil: true

  self.per_page = 10

  def belongs_to?(user)
    return false unless user.present?
    user_id == user.id
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include RailsAdmin::Tag

  has_many :tagables
  has_many :snippets, through: :tagables, source: :snippet

  validates :title, presence: true
end

app/models/tagable.rb
class Tagable < ActiveRecord::Base
  belongs_to :snippet
  belongs_to :tag 

  validates :snippet, presence: true
  validates :tag    , presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :snippets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_by_email(request.env['omniauth.auth']['info']['email'].downcase)

    unless @user
      return redirect_to root_url, alert: 'Could not sign you in because your account does not exist.'
    end

    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
  end

  def after_sign_in_path_for(resource)
    super resource
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index  
    @snippets = Snippet.all.recent.paginate(page: page_param)
  end

  def my_gists  
    @snippets = Snippet.where(user: current_user).recent.paginate(page: page_param) if current_user
  end

  def show
    @snippet = Snippet.find(snippet_id)
    render :show
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(create_params)

    if @snippet.save
      redirect_to snippets_url, notice: 'Snippet created successfully.'
    else
      render :new
    end
  end

  def edit
    @snippet = Snippet.find(snippet_id)
    unless @snippet.belongs_to?(current_user)
      redirect_to snippets_url, notice: 'You are not allowed to edit this snippet'
    end
  end

  def update
    @snippet = Snippet.find(snippet_id)
    unless @snippet.belongs_to?(current_user)
      return redirect_to snippets_url, notice: 'You are not allowed to update this snippet'
    end

    if @snippet.update_attributes(update_params)
      redirect_to snippet_url(@snippet), notice: "Snippet updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @snippet = Snippet.find(snippet_id)
    
    unless @snippet.belongs_to?(current_user)
      return redirect_to snippets_url, notice: 'You are not allowed to delete this snippet'
    end

    flash[:notice] = "Snippet deleted successfully." if @snippet.destroy
    redirect_to snippets_url
  end

  def search
    @snippets = Snippet.where("title ILIKE ? OR content ILIKE ?", "%#{keyword}%", "%#{keyword}%").recent.paginate(page: page_param)
    @keyword = keyword
    render :index
  end

  def share_form
    @snippet = Snippet.find(snippet_id)
  end

  def share
    @snippet = Snippet.find snippet_id

    SnippetNotifier.snippet_sharing(
      sharer: current_user, 
      share_email: share_email,
      snippet: @snippet
    ).deliver
    
    redirect_to snippet_url(@snippet), notice: "Snippet was shared successfully to #{share_email}"
  end

  private
  def page_param
    params.fetch :page, 1
  end

  def create_params
    params.require(:snippet).permit(
      :title, :status, :email, :content, tag_ids: []
    ).merge(user: current_user)
  end

  def update_params
    create_params
  end

  def share_email
    params.require(:snippet).permit(:email)[:email]
  end

  def snippet_id
    params.require(:id)
  end

  def keyword
    params.fetch(:q, '')
  end
end

app/helpers/application_helper.rb
class HtmlWithPygments < Redcarpet::Render::HTML
  def check_language_available(language)
    Pygments.lexers.select { |key, lexer| lexer[:aliases].include? language }.present?
  end

  def block_code(code, language)
    options = {options: {linespans: 'line'}}
    options.merge!(lexer: language) if check_language_available(language)
    Pygments.highlight(code, options)
  end
end

module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(HtmlWithPygments, fenced_code_blocks: true, disable_indented_code_blocks: true)
    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.slim
html
  head
    title Gist
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container-fluid
      .row
        = render 'shared/main_menu'
        = render 'shared/notice'
        
        .container = yield

app/views/layouts/application.slim
html
  head
    title Gist
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      = render 'shared/notice'

      = render 'shared/main_menu'
      = render 'shared/search_bar'
      
      = yield

app/views/shared/_main_menu.slim
nav.navbar.navbar-default.bg-success
  .container
    .row
      .navbar-header
        = link_to "Neember Gists", snippets_path, class: "navbar-brand"

      = render partial: 'shared/search_bar'
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = link_to icon('user', current_user.username), '#'
          li = link_to icon('list-alt', 'My Gists'), my_gists_snippets_path
          li = link_to icon('plus', 'Create a gist'), new_snippet_path
          li = link_to icon('sign-out', 'Sign out'), destroy_user_session_path, method: :delete
        - else
          li = link_to 'Sign in with Google', user_omniauth_authorize_path(provider: :google_oauth2)

app/views/shared/_notice.slim
.container
  .row
    - if notice.present?
      p.alert.alert-info = notice
    - if alert.present?
      p.alert.alert-info = alert

app/views/shared/_search_bar.slim
= form_tag search_snippets_path, method: :get, class: 'navbar-form navbar-left form-inline', role: 'form' do 
  .form-group
    = text_field_tag 'q', @keyword, class: "form-control", placeholder: 'Enter your keyword'
  | &nbsp;
  = button_tag icon('search', 'Search'), class: 'btn btn-default'

app/views/snippets/_buttons.slim
.btn-group.btn-group-sm.share-group
  = link_to icon('share', 'Share'), share_snippet_path(snippet), class: 'btn text-info'
  - if snippet.belongs_to?(current_user)
    = link_to icon('edit', 'Edit'), edit_snippet_path(snippet), class: 'btn text-success' 
    = link_to icon('trash', 'Delete'), snippet_path(snippet), 
      method: :delete, class: 'btn text-danger', 
      data: {confirm: "You cannot undo this action. Are you sure you want to delete?"}

app/views/snippets/_form.html.slim
= simple_form_for @snippet, html: {name: 'snippet_form'} do |form|
  .col-md-12.text-right
    .row = form.submit class: 'btn btn-success'
  h2.page-header = form_title
  = form.input :title
  = form.input :content, hint: 'Markdown syntax is supported.'

app/views/snippets/_form.slim
.snippets-form-container
  = simple_form_for @snippet do |snippet|
    = snippet.input :title
    = snippet.input :status, :as => :select, :collection => Snippet.statuses.keys.to_a
    = snippet.association :tags,   as: :check_boxes
    = snippet.button :submit

app/views/snippets/_index.slim
.list-group
  - snippets.each do |snippet|
    .snippet.list-group-item
      = link_to snippet.title, snippet_path(snippet)
      = render partial: 'snippets/buttons', locals: {snippet: snippet}

app/views/snippets/edit.html.slim
= render partial: 'snippets/form', locals: {form_title: "Edit #{@snippet.title}"}

app/views/snippets/index.html.slim
.row
  h2.page-header List of Snippets

  = render partial: 'snippets/index', locals: {snippets: @snippets}
  = will_paginate @snippets, renderer: BootstrapPagination::Rails
  

app/views/snippets/index.slim
#snippets-index-container
  h2 Snippet listing

  table.table.table-striped
    thead
      tr
        th Title
        th Date
        th 
        th
        th
    tbody
      - @snippets.each do |snippet|
        tr
          td = link_to snippet.title, snippet_path(snippet)
          td= snippet.created_at.strftime("%A, %d/%m/%Y")
          td
            = link_to 'Detail', snippet_path(snippet), class: 'btn btn-default'
          td
            - if snippet.belongs_to?(current_user)
              = link_to 'Edit', edit_snippet_path(snippet), class: 'btn btn-default'
          td
            - if snippet.belongs_to?(current_user)
              = link_to 'Delete', snippet_path(snippet), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" }

app/views/snippets/my_gists.slim
#snippets-index-container
  h2 My gists

  table.table.table-striped
    thead
      tr
        th Title
        th Date
        th 
        th
        th
    tbody
      - @snippets.each do |snippet|
        tr
          td = link_to snippet.title, snippet_path(snippet)
          td= snippet.created_at.strftime("%A, %d/%m/%Y")
          td
            = link_to 'Detail', snippet_path(snippet), class: 'btn btn-default'
          td
            - if snippet.belongs_to?(current_user)
              = link_to 'Edit', edit_snippet_path(snippet), class: 'btn btn-default'
          td
            - if snippet.belongs_to?(current_user)
              = link_to 'Delete', snippet_path(snippet), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" }

app/views/snippets/new.html.slim
= render partial: 'snippets/form', locals: {form_title: 'New Snippet'}

app/views/snippets/new.slim
#snippets-new-container
  h1 Create a snippet
  = render 'snippets/form'

app/views/snippets/share_form.html.slim
.snippets-share-form-container
  = simple_form_for [:share, @snippet], method: :post do |f|
    = f.input :email, hint: 'Emails are separated by comma e.g. john@example.com, jack@example.com'
    = f.submit 'Share this gist', class: 'btn btn-info'

app/views/snippets/share_form.slim
.snippets-share-form-container
  = simple_form_for [:share, @snippet], method: :post do |f|
    = f.input :email
    = f.submit 'Share to this email'

app/views/snippets/show.html.slim
.row
  h2.page-header = @snippet.title
  .panel.panel-default
    .panel-heading
      label.label.label-primary = @snippet.username
      = render partial: 'snippets/buttons', locals: {snippet: @snippet}
    .panel-body
      .markdown-body = markdown @snippet.content
  #disqus_thread

javascript:
  var disqus_shortname = 'neembergist';

  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
  

app/views/snippets/show.slim
#snippets-show-container
  h1 = @snippet.title
  - if @snippet.belongs_to?(current_user)
    .btn-group
      = link_to 'Share this gist', share_snippet_path(@snippet), class: 'btn btn-success'
      = link_to 'Edit', edit_snippet_path(@snippet), class: 'btn btn-default'
      = link_to 'Delete', snippet_path(@snippet), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" }